services:
    app:
        build: .
        user: '${USER_ID}:${GROUP_ID}'
        ports:
            - '8080:${APP_PORT}'
            - '5173:5173'
        volumes:
            - .:/app:z
            - /home/serhii/www/open/textwire/textwire:/textwire:z
            - go-pkg:/go/pkg:z
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_CHARSET: utf8mb4
            MYSQL_COLLATION: utf8mb4_unicode_ci
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - serhiicho-db:/var/lib/mysql:z
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
        networks:
            - internal

networks:
    internal:
        driver: bridge

volumes:
    serhiicho-db:
        driver: local
    go-pkg:
        driver: local
