FROM golang:1.25-trixie

RUN apt-get update

RUN apt-get install -y \
        nodejs \
        npm && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.* ./
COPY package.* ./

RUN go mod download && npm i

COPY . .

CMD ["go", "run", "./cmd/blog"]
