FROM golang:1.25-trixie

RUN apt-get update

RUN apt-get install -y \
        nodejs \
        npm && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.* ./
COPY package.* ./

COPY . .

RUN go build ./cmd/blog && npm i

ENTRYPOINT ["./blog"]
